name: Daily Scrum Generator

# 스케줄과 수동 실행 트리거 추가
on:
  schedule:
    - cron: '15 0 * * *'  # 매일 0시 15분 (한국 시간 기준 9시 15분)
  workflow_dispatch:     # 수동 실행 트리거 추가

jobs:
  create_daily_scrum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 git 기록을 가져와 충돌 방지

      - name: Create Daily Scrum Markdown File
        id: create_file  # ID를 설정하여 이후 단계에서 파일 이름을 참조할 수 있도록 함
        run: |
          DATE=$(date +"%Y-%m-%d")
          FILE_NAME="daily-scrum-$DATE.md"
          echo "## Team Mission" > $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 당일에 한 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 내일 할 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 미해결 문제" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 기타 사항" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "--------" >> $FILE_NAME
          echo "## Study Log" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 당일에 한 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 내일 할 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 미해결 문제" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 기타 사항" >> $FILE_NAME
          echo "-" >> $FILE_NAME

          # 파일 이름을 출력하여 다음 단계에서 참조할 수 있도록 설정
          echo "file_name=$FILE_NAME" >> $GITHUB_ENV

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # 1. 원격 저장소 최신 상태를 로컬로 가져오기 (pull)
          git pull origin main --rebase
          
          # 2. 변경 사항 추가 및 커밋
          git add .
          git commit -m "Add daily scrum file for $DATE" || echo "No changes to commit"
          
          # 3. 강제 푸시 (--force-with-lease 옵션 사용)
          git push origin main --force-with-lease
