name: Daily Scrum Generator

# 매일 오전 9시에 작업 실행 (UTC 기준, 한국 시간은 UTC+9이므로 0시로 설정)
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 0시 (한국 시간 기준 9시)

jobs:
  create_daily_scrum:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. 데일리 스크럼 양식 생성
      - name: Create Daily Scrum Markdown File
        run: |
          # 현재 날짜를 기반으로 파일 이름 설정
          DATE=$(date +"%Y-%m-%d")
          FILE_NAME="daily-scrum-$DATE.md"

          # 데일리 스크럼 및 Study Log 양식 작성
          echo "## Team Mission" > $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 당일에 한 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 내일 할 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 미해결 문제" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 기타 사항" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "--------" >> $FILE_NAME
          echo "## Study Log" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 당일에 한 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 내일 할 작업" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 미해결 문제" >> $FILE_NAME
          echo "-" >> $FILE_NAME
          echo "" >> $FILE_NAME
          echo "### 기타 사항" >> $FILE_NAME
          echo "-" >> $FILE_NAME

      # 3. 생성된 파일을 커밋 및 푸시
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add daily scrum file for $DATE"
          git push
